version: '3.4'

services:
  authmicroservice.api:
    image: ${DOCKER_REGISTRY-}authmicroserviceapi
    build:
      context: .
      dockerfile: Microservices/AuthMicroservice/AuthMicroservice.API/Dockerfile

  recipemicroservice.api:
    image: ${DOCKER_REGISTRY-}recipemicroserviceapi
    build:
      context: .
      dockerfile: Microservices/RecipeMicroservice/RecipeMicroservice.API/Dockerfile


  reviewmicroservice.api:
    image: ${DOCKER_REGISTRY-}reviewmicroserviceapi
    build:
      context: .
      dockerfile: Microservices/ReviewMicroservice/ReviewMicroservice.API/Dockerfile

  sqlserver:
    container_name: sqldb
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sqlserver